---
- action:
    module: "{{packager}}"
    name: vim

- name: add vim rc files
  copy:
    src: "{{item}}"
    dest: "/home/{{user}}/{{item}}"
  with_items:
    - .vimrc
    - .gvimrc
    - .vim

- name: add vim themes
  copy:
    src: .vim
    dest: "/home/{{user}}/.vim"
