theme = "solarized-dark"
icons = "awesome5"

# [[block]]
# block = "pacman"
# interval = 600
# format = "{pacman} + {aur} = {both} updates available"
# format_singular = "{both} update available"
# format_up_to_date = "system up to date"
# critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
# aur_command = "pikaur -Qua"
[[block]]
block = "pacman"
critical_updates_regex = "zfs"

[[block]]
block = "time"
interval = 60
format = "%R %Z"
timezone = "UTC"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m} {5m}"
info = 2.0
warning = 4.0
critical = 6.0

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "networkmanager"
primary_only = true

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "music"
marquee = false
smart_trim = true

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %R"
